class LocationModel {
  final String addr1,
      addr2,
      areacode,
      booktour,
      cat1,
      cat2,
      cat3,
      contentid,
      contenttypeid,
      cpyrhtDivCd,
      createdtime,
      dist,
      firstimage,
      firstimage2,
      mapx,
      mapy,
      mlevel,
      modifiedtime,
      sigungucode,
      tel,
      title;

  LocationModel.fromJson(Map<String, dynamic> json)
      : addr1 = json['addr1'],
        addr2 = json['addr2'],
        areacode = json['areacode'],
        booktour = json['booktour'],
        cat1 = json['cat1'],
        cat2 = json['cat2'],
        cat3 = json['cat3'],
        contentid = json['contentid'],
        contenttypeid = json['contenttypeid'],
        cpyrhtDivCd = json['cpyrhtDivCd'],
        createdtime = json['createdtime'],
        dist = json['dist'],
        firstimage = json['firstimage'],
        firstimage2 = json['firstimage2'],
        mapx = json['mapx'],
        mapy = json['mapy'],
        mlevel = json['mlevel'],
        modifiedtime = json['modifiedtime'],
        sigungucode = json['sigungucode'],
        tel = json['tel'],
        title = json['title'];
}
